### ISSUE TITLE
Didn't receive transfer from myetherwallet

### ISSUE THREAD

**Issue by aequitas28** [ETCDEVTeam/emerald-wallet#648]
I tried to transfer ETC from myetherwallet to Emerald Wallet. It's been 2 days, and I still haven't received the transfer.
https://gastracker.io/tx/0xb5678d934023f1354ff643edaf8c2181cf1b1d02caa2bf39e741d45905e1507e
[https://gastracker.io/tx/0xb5678d934023f1354ff643edaf8c2181cf1b1d02caa2bf39e741d45905e1507e](url)
There is the gastracker. The only thing that is weird is I used the copy link from the app. Which shows as mostly lower case letters. 0xb1e0b17c6032d266e1b14ecbcbc1a7730f8f320b
However on gastracker, it shows my address with majority uppercase letters. 
0xB1e0B17C6032d266e1b14eCBCBC1A7730f8F320b
Would that affect my ability to receive the transaction? 
Any help would be appreciated. Thanks.

**Comment by shanejonas** [comment]
We've update the wallet to update your tx history periodically so this should be solved now

**Comment by aequitas28** [comment]
ok thank you. 
I actually figured out how to locate it. I had my node set to "Mainnet Full Node". Which still shows no balance. However when I select:
Mainnet (gastracker.io) Light Node or Mainnet (epool.io) Light Node. 
Both options allow my balance to show up. 
Thanks for your time.

**Comment by shanejonas** [comment]
Ah, maybe your node isn't fully synced yet. The next upcoming release should have a better indication for sync %

**Comment by bjzy** [comment]
Looking forward to the new release to help troubleshoot this. Like @aequitas28 I can see that the Mainnet full node is not showing my transfer/balance. If I switch to either light node, I can see my balance just fine. This is my first ETC test... 

http://gastracker.io/addr/0x01452079702422900a9547f75134085218427dd5

That transaction shows fine on either light node. 

However, my full node says it's sync'd through block 6046696 which should include the block my transaction was in (6045549), but it doesn't show anything.

![screen shot 2018-06-22 at 1 45 11 pm](https://user-images.githubusercontent.com/496756/41798511-c5e2aeda-7622-11e8-8515-ad2fa41b9d51.png)
